<h3>add organizer</h3><br>

<?php
$form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?php
    $lastname = $form->get('lastname');
    echo $this->formLabel($lastname);
    echo $this->formText($lastname);
    echo $this->formElementErrors($lastname);
    ?>
</div>

<div class="form-group">
    <?php
    $firstname = $form->get('firstname');
    echo $this->formLabel($firstname);
    echo $this->formText($firstname);
    echo $this->formElementErrors($firstname);
    ?>
</div>

<div class="form-group">
    <?php
    $email = $form->get('email');
    echo $this->formLabel($email);
    echo $this->formEmail($email);
    echo $this->formElementErrors($email);
    ?>
</div>

<?= $this->formRow($form->get('submit')) ?> <br>

<?= $this->form()->closeTag($form); ?>