<div class="jumbotron">
    <p>add</p>

    <?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
    ?>

    <?= $this->form()->openTag($form); ?>

    <?= $this->formRow($form->get('title')) ?> <br>
    <?= $this->formRow($form->get('description')) ?> <br>
    <?= $this->formRow($form->get('startingDate')) ?> <br>
    <?= $this->formRow($form->get('endingDate')) ?> <br>
    <?= $this->formRow($form->get('img')) ?> <br>
    <?= $this->formSubmit($form->get('submit')); ?>

    <?= $this->form()->closeTag($form); ?>
</div>