<div class="jumbotron">
    <p>Liste des meetups :</p>
    <a href="<?= $this->url('meetup/add') ?>">Ajouter un meetup</a>
    <br><br>

    <ul>
        <?php foreach ($meetups as $meetup): ?>
            <li>
                <a href="<?php echo $this->url('meetup/view', ['id' => $meetup['id']]) ?>"><?php echo $meetup['title'] ?></a>
                <?php echo $meetup['startingDate']->format('d-m-Y') ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>