<h3>New meetup available !</h3>
<?php echo $newMeetup->getTitle() ?><br>
<?php echo $newMeetup->getStartingDate()->format('d-m-Y') ?><br>
<a href="<?php echo $this->url('meetup/view', ['id' => $newMeetup->getId()]) ?>">read more</a>

<br><br>
<h3>Next meetup</h3>
<?php echo $nextMeetup->getTitle() ?><br>
<?php echo $nextMeetup->getStartingDate()->format('d-m-Y') ?><br>
<a href="<?php echo $this->url('meetup/view', ['id' => $nextMeetup->getId()]) ?>">read more</a>
